### ISSUE TITLE
Note on U109, XCLKEN

### ISSUE THREAD

**Issue by jasonsbeer** [jasonsbeer/Amiga-2000-EATX#23]
ISSUE: The XCLKEN pin is lacking a pullup resistor, which could result in the 74HC258 switching to the XCLK signal when there is not one present.

SEVERITY: There have been several reports of this happening. 

SCOPE: Rev 2.x boards only.

PROPOSED FIX: In the event you do not get a 28MHz clock from pin 12 of U109, add a 10k pullup to pin 1 of U109. You can attach the pullup to any +5V source. C109 is nearest. Target future revision for fix.

History
Jul-13-2022 Original report.
Nov-27-2022 Updated severity.

**Comment by jasonsbeer** [comment]
Added to Revision 3.0.

**Comment by Sgw32** [comment]
Confirm this thing. Had this on a fully working board, and it started to shut down while working.
