### ISSUE TITLE
A500 - ram-expansion port

### ISSUE THREAD

**Issue by pluspeople** [jasonsbeer/Amiga-2000-EATX#28]
ISSUE: A A314 expansion can not be used on the B2000 EATX board.

SEVERITY: Enhancement request.

SCOPE: Future revision.

PROPOSED: Add the option for a pin-header similar to the A500 ram expansion, on the B2000 board, potentially just above the ram-chip - leave it as an option so people can choose not to populate this pin-header if they have no desire for this feature.

BACKGROUND/MOTIVATION:
The A314 expansion is a game-changer in what is possible with an Amiga, since it has direct access to the chip-ram bus it can do some truly amazing stuff - chip-ram on steriods!
However a normal A2000 has no way of using this great new expansion, which means that it is limited to only being used in the A500/600. 
The B2000 could change this, since the A2000 essentially is an A500 architecture, it should not be difficult to find the pins required for the ram-slot - I imagine they are all near the agnus and/or ram-chip, and a simple un-populated pinheader on the pcb with these connections would make it possible to "insert" the A314 vertically ontop of the board and essentially take over the chip-ram handling of the computer... A314 & Zorro slots what a combo.

**Comment by jasonsbeer** [comment]
The appropriate way to expand the A2000 is by way of the Zorro 2 bus. This will be a bespoke connector for a single device. In addition, real estate will be an issue.
