### ISSUE TITLE
20 pin ATX power supplies and SMD oscillator

### ISSUE THREAD

**Issue by thepillock** [jasonsbeer/Amiga-2000-EATX#30]
ISSUE: Does not start up when 20pin PSU is used and SMD oscillator has been installed

Pin 12 on the ATX connector is 3.3v, and supplies power to the SMD oscillator. When a 20-pin PSU is used, pins 11/12/23/24 are missing and although 11/23/24 are connected to their equivalents elsewhere on the connector (i.e. 11 is connected to 10, 23 connected to 22, 24 connected to all other GND) pin 12 isn't connected to any other 3.3v pins so the oscillator doesn't get power.

(Thanks to LIV2 on Discord for working out where Pin12 was going)

TEMP SOLUTION 1: Short Pin 12 to 1 to provide power to the oscillator (verified - it boots like this)
TEMP SOLUTION 2: Use TH oscillator (not verified, can't see why it wouldn't work)

**Comment by jasonsbeer** [comment]
Updated ATX power connector to include all +3.3V inputs.
