### ISSUE TITLE
Q: Will there be any chance of getting hold an mostly ready board for us with disatreous soldering skills?

### ISSUE THREAD

**Issue by janderssonse** [jasonsbeer/Amiga-2000-EATX#33]
This project looks amazing, I bet there are quite a few out there, including me, that don't have the skills,. nor the time free to learn the skills needed to succesfully order a board and make it a reality, i.e ready to put in a case. I fully understand that you the creator might  rather want to perfect the design than to build and ship pre-populated boards, but have any of the regular amiga dealers( the few that ar active) showed any interest in this.Or is there any other way to obtain a mostly complete board, or plans for a more user ready viersion?

**Comment by jasonsbeer** [comment]
I recommend you visit the Discord channel and open a discussion there. There have been previous runs of "mostly assembled" boards that were started by members of the community. Might be some interest and doing another.

https://discord.gg/NU7SPYfNFj

I have not been approached by anyone about doing runs for commercial sales.

**Comment by janderssonse** [comment]
Thanks for the quick response, will join! Cheers!
